version: 2

models:
  - name: fact_orders
    description: "Central fact table with one row per order. Includes payment, review, and delivery info."
    columns:
      - name: order_id
        description: "Primary key for the order."
        tests: [unique, not_null]

      - name: customer_id
        description: "FK to dim_customers."
        tests: [not_null]

      - name: order_status
        description: "Status of the order."

      - name: order_date
        description: "Date the order was placed."

      - name: total_payment
        description: "Total payment amount for the order."

      - name: payment_type
        description: "Payment method used for the order."

      - name: review_score
        description: "Customer review score for the order."

      - name: number_of_items
        description: "Total number of items in the order."

      - name: total_price
        description: "Sum of item prices in the order."

      - name: total_freight
        description: "Total freight cost of the order."

      - name: product_id
        description: "Representative product from the order. FK to dim_products."

      - name: seller_id
        description: "Representative seller from the order. FK to dim_sellers."

  - name: dim_customers
    description: "Customer dimension table with location details."
    columns:
      - name: customer_unique_id
        tests: [unique, not_null]

      - name: representative_customer_id
        description: "Example customer_id used for this unique customer."

  - name: dim_products
    description: "Product dimension table with category and physical attributes."
    columns:
      - name: product_id
        tests: [unique, not_null]

      - name: product_category_name
      - name: product_category_name_english

  - name: dim_sellers
    description: "Seller dimension table with ZIP and location info."
    columns:
      - name: seller_id
        tests: [unique, not_null]

  - name: dim_dates
    description: "Date dimension table seeded from CSV. Contains calendar-related columns."
    columns:
      - name: calendar_date
        tests: [unique, not_null]

      - name: year
      - name: month
      - name: day